
server:
  port: ${PORT:9092}

spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 275467666884234
            client-secret: 18c6977e20cb1374b2085df443aa684d
            scope:
              - email
              - public_profile
          google:
            clientId: 747054116050-j25974gvn8i27h044kdddi3714rr8s74.apps.googleusercontent.com
            clientSecret: EitCAZgKbH-Ae0ymTBLJJoVG
#          linkedin:
#            clientId: 78a8aiizlexnwb
#            clientSecret: 8XxCHnU2F4pGhoKn
#        provider:
#          linkedin:
#            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
#            token-uri: https://www.linkedin.com/uas/oauth2/accessToken
#            user-info-uri: https://api.linkedin.com/v2/me
#            jwk-set-uri:
#            user-name-attribute: id


# ===============================
# = JPA configurations
# ===============================
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true

# ===============================
# = MAIL configurations
# ===============================
  mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      username: new.news.feed.2020@gmail.com
      password: guxzgbeckqxrlisn
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      protocol: smtp
      test-connection: false

