server:
  port: ${PORT:5000}


# ===============================
# = UPLOAD configurations
# ===============================

multipart:
    enabled: true

servlet:
    multipart:
      max-file-size: 10000000


http:
    multipart:
      max-request-size: 500000KB




spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dreamgirl15



# ===============================
# = JPA configurations
# ===============================
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true

# ===============================
# = MAIL configurations
# ===============================
  mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      username: new.news.feed.2020@gmail.com
      password: guxzgbeckqxrlisn
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      protocol: smtp
      test-connection: false

